/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import clases.Conexion;


//librerias para la tabla
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

//librerias para interactuar con la tabla
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Yader Jr
 */
public class GestionarEquipos extends javax.swing.JFrame {

    /**
     * Creates new form GestionarClientes
     */
    
    String user;
    
    //variable para enviar datos entre interfaces tipo static y encapsulamiento publico
    //servira para saber cual es el usuario que se esta consultando
  //  public static String user_update = "";
    
    public static int IDCEquipo_update = 0;
    
    DefaultTableModel model = new DefaultTableModel();
    
    public GestionarEquipos() {
        initComponents();
        
        user = Login.user;
        
        setSize(630,380);
        setTitle("Equipos registrados - sesión de "+user);
        setResizable(false);
        setLocationRelativeTo(null);
        
        //metodo para que no se cierre todo el programa cuando se cierra esta interfaz
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
           ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");

        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(), label_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));

        label_wallpaper.setIcon(icono);

        this.repaint();
        
        try
        {
            
            Connection cn = Conexion.db();
            PreparedStatement pst = cn.prepareStatement("select id_equipo, tipo_equipo, marca, estatus  from equipos");
            
            ResultSet rs = pst.executeQuery();
            
            tabla_equipos_registrados = new JTable(model);
            
            jScrollPane1.setViewportView(tabla_equipos_registrados);
            
            model.addColumn("");
            model.addColumn("Tipo");
            model.addColumn("Marca");
            model.addColumn("Estatus");

            
           while (rs.next())
            {
                
                Object[] fila = new Object[4]; 
                
                for (int i = 0; i < 4; i++)
                {
                    
                    fila[i] = rs.getObject(i+1);
                    
                }
                model.addRow(fila);
            }
           cn.close();
            
        } catch (SQLException e)
        {
            System.err.println("Error en mostrar los equipos en la tabla"+e);
            JOptionPane.showMessageDialog(null, "Error en cargar datos de los equipos registrados, contacte al administrador");
        }
        
        ObtenerDatosTabla();
           
    }
    

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_equipos_registrados = new javax.swing.JTable();
        label_header = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        button_mostrar = new javax.swing.JButton();
        jcombobox_estatus = new javax.swing.JComboBox<>();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_equipos_registrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_equipos_registrados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 180));

        label_header.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label_header.setForeground(new java.awt.Color(255, 255, 255));
        label_header.setText("Equipos registrados");
        getContentPane().add(label_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 5, -1, -1));

        label_footer.setForeground(new java.awt.Color(0, 0, 0));
        label_footer.setText("Creado por Yader Barahona");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        button_mostrar.setBackground(new java.awt.Color(153, 153, 255));
        button_mostrar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        button_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        button_mostrar.setText("Mostrar");
        button_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(button_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, 30));

        jcombobox_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo ingreso", "No reparado", "En revision", "Reparando", "Entregado" }));
        jcombobox_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobox_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(jcombobox_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 130, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mostrarActionPerformed
   
       String query = "";
       
       //metodo setrow o columncount para limpiar las filas de la tabla
       model.setRowCount(0);
       model.setColumnCount(0);
       
       String seleccion = jcombobox_estatus.getSelectedItem().toString();

         try{    
                Connection cn = Conexion.db();
                
        //condicional para el filtro de busqueda de la palabra contenida en el combobox
        if (seleccion.equalsIgnoreCase("Todos"))
        {
        
             query = "Select id_equipo, tipo_equipo, marca, estatus from equipos";

        } else {
                //comilla simple se usa para indicar que la variable que se está asignando es un campo con ese valor dentro de la db y no la tome como una columna
                query = "Select id_equipo, tipo_equipo, marca, estatus from equipos where estatus ='"+seleccion+"'";
     
        }  
        
          PreparedStatement pst = cn.prepareStatement(query);
          ResultSet rs = pst.executeQuery();
                
         tabla_equipos_registrados = new JTable(model);
            
         jScrollPane1.setViewportView(tabla_equipos_registrados);
            
            model.addColumn("");
            model.addColumn("Tipo");
            model.addColumn("Marca");
            model.addColumn("Estatus");
            
            JOptionPane.showMessageDialog(null, "Estatus seleccionado: "+seleccion);

            
           while (rs.next())
            {
                
                Object[] fila = new Object[4]; 
                
                for (int i = 0; i < 4; i++)
                {
                    
                    fila[i] = rs.getObject(i+1);
                    
                }
                model.addRow(fila);
            }
           cn.close();
            } catch (SQLException e)
            {
                
                System.err.println("Error al recuperar los registros de equipo"+e);
                
            }
         
         ObtenerDatosTabla();
        
    }//GEN-LAST:event_button_mostrarActionPerformed

    private void jcombobox_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobox_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombobox_estatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_mostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcombobox_estatus;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTable tabla_equipos_registrados;
    // End of variables declaration//GEN-END:variables

public void ObtenerDatosTabla (){
        tabla_equipos_registrados.addMouseListener(new MouseAdapter(){
            
            @Override
            public void mouseClicked(MouseEvent e){
                
                int fila_point = tabla_equipos_registrados.rowAtPoint(e.getPoint());
                
                int columna_point = 0;
                
                if (fila_point>-1)
                {
                    IDCEquipo_update = (int) model.getValueAt(fila_point, columna_point);
                    
                    JOptionPane.showMessageDialog(null, "El id del equipo seleccionado es: "+IDCEquipo_update);
                    
                    InformacionEquiposTecnico informacion_equipos_tecnico = new InformacionEquiposTecnico();
                    
                    informacion_equipos_tecnico.setVisible(true);
                    
                    
                }
                
            }
        
        
    });
}

}
