/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Yader Jr
 */
public class InformacionEquipos extends javax.swing.JFrame {

    /**
     * Creates new form InformacionEquipos
     */
    
      int IDCliente_update;
     String user = "", nom_cliente = "";
     int IDEquipo;
    
    public InformacionEquipos() {
        initComponents();
        
        setSize(670, 530);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
      
        IDEquipo = InformacionCliente.ID_equipo;

        user = Login.user;
        IDCliente_update = GestionarClientes.IDCliente_update;

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");

        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(), label_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));

        label_wallpaper.setIcon(icono);
        this.repaint();
        
         try
        {
            Connection cn = Conexion.db();
            //instruccion hacia la db para indicar cual id estamos consultando
            PreparedStatement pst = cn.prepareStatement("select nombre_cliente from clientes where id_cliente = '" + IDCliente_update + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next())
            {
                nom_cliente = rs.getString("nombre_cliente");
                

            }

            cn.close();

        } catch (SQLException e)
        {
            System.err.println("Error en cargar cliente" + e);
            JOptionPane.showMessageDialog(null, "Error al cargar, contacte al administrador");
        }
        
        txt_nombre.setText(nom_cliente);
         setTitle("Equipo del cliente " + nom_cliente);
         
          try
        {
            Connection cn2 = Conexion.db();
            PreparedStatement pst = cn2.prepareStatement("select * from equipos where id_equipo = '" + IDEquipo + "'");

            ResultSet rs= pst.executeQuery();

            if (rs.next())
            {

                //a cada txt le ponemos el nombre y demas propiedades del registro que haya seleccionado de la tabla esto por el metodo setText y llamando al objeto rs con el metodo getString (campo o columna que se vaya a recuperar de la db)
                txt_modelo.setText(rs.getString("modelo"));
                txt_numero_serie.setText(rs.getString("num_serie"));
                txt_ultima_modificacion.setText(rs.getString("ultima_modificacion"));

                combobox_tipo_equipo.setSelectedItem(rs.getString("tipo_equipo"));
                combobox_marca.setSelectedItem(rs.getString("marca"));
                combobox_estatus.setSelectedItem(rs.getString("estatus"));
                
                String dia = "", mes = "", annio = "";
                
                //valores para la fecha tomados desde la db ya que esta por dia mes y año
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("annio_ingreso");
                
                txt_fecha.setText(dia +" del "+ mes +" del " +annio);
                
                jTextPane_daños.setText(rs.getString("Observaciones"));
                jTextPane_comentarios.setText(rs.getString("comentarios_tecnicos"));
                
                label_comentarios.setText("Comentarios y actualizacion del técnico "+rs.getString("revision_tecnica_de"));
               
            }

            cn2.close();

        } catch (SQLException e)
        {
            System.err.println("Error en cargar usuario" + e);
            JOptionPane.showMessageDialog(null, "Error al cargar, contacte al administrador");
        }
    }
        
    
    
       @Override
    public Image getIconImage() {
        //no necesita especificar la carpeta src el metodo ya sabe que se va a usar un archivo de esta carpeta
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_titutlo = new javax.swing.JLabel();
        label_tipo_equipo = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        label_modelo = new javax.swing.JLabel();
        label_numero_serie = new javax.swing.JLabel();
        label_ultima_modificacion = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        label_reportes = new javax.swing.JLabel();
        label_comentarios = new javax.swing.JLabel();
        label_estatus = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_numero_serie = new javax.swing.JTextField();
        txt_ultima_modificacion = new javax.swing.JTextField();
        combobox_tipo_equipo = new javax.swing.JComboBox<>();
        combobox_marca = new javax.swing.JComboBox<>();
        combobox_estatus = new javax.swing.JComboBox<>();
        txt_fecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_daños = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_comentarios = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        label_nombre.setText("Nombre del cliente:");
        getContentPane().add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        label_titutlo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label_titutlo.setForeground(new java.awt.Color(255, 255, 255));
        label_titutlo.setText("Información del equipo");
        getContentPane().add(label_titutlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        label_tipo_equipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_tipo_equipo.setForeground(new java.awt.Color(255, 255, 255));
        label_tipo_equipo.setText("Tipo de equipo:");
        getContentPane().add(label_tipo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        label_marca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_marca.setForeground(new java.awt.Color(255, 255, 255));
        label_marca.setText("Marca:");
        getContentPane().add(label_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        label_modelo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_modelo.setForeground(new java.awt.Color(255, 255, 255));
        label_modelo.setText("Modelo:");
        getContentPane().add(label_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        label_numero_serie.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_numero_serie.setForeground(new java.awt.Color(255, 255, 255));
        label_numero_serie.setText("Número de serie:");
        getContentPane().add(label_numero_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        label_ultima_modificacion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_ultima_modificacion.setForeground(new java.awt.Color(255, 255, 255));
        label_ultima_modificacion.setText("Última modificación por:");
        getContentPane().add(label_ultima_modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        label_fecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_fecha.setForeground(new java.awt.Color(255, 255, 255));
        label_fecha.setText("Fecha de ingreso:");
        getContentPane().add(label_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        label_reportes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_reportes.setForeground(new java.awt.Color(255, 255, 255));
        label_reportes.setText("Daño reportado y observaciones");
        getContentPane().add(label_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        label_comentarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_comentarios.setForeground(new java.awt.Color(255, 255, 255));
        label_comentarios.setText("Comentarios y actualizacion del técnico");
        getContentPane().add(label_comentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        label_estatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_estatus.setForeground(new java.awt.Color(255, 255, 255));
        label_estatus.setText("Estatus");
        getContentPane().add(label_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        txt_nombre.setEditable(false);
        txt_nombre.setBackground(new java.awt.Color(209, 219, 218));
        txt_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 25));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 25));

        txt_numero_serie.setBackground(new java.awt.Color(153, 153, 255));
        txt_numero_serie.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_numero_serie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_numero_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 25));

        txt_ultima_modificacion.setEditable(false);
        txt_ultima_modificacion.setBackground(new java.awt.Color(209, 219, 218));
        txt_ultima_modificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_ultima_modificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_ultima_modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 25));

        combobox_tipo_equipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        combobox_tipo_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(combobox_tipo_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        combobox_marca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        combobox_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "alienware", "Apple", "Asus", "Brother", "Dell ", "HP", "Lenovo" }));
        getContentPane().add(combobox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        combobox_estatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        combobox_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revision", "Reparado", "Entregado" }));
        getContentPane().add(combobox_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 120, -1));

        txt_fecha.setEditable(false);
        txt_fecha.setBackground(new java.awt.Color(209, 219, 218));
        txt_fecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 180, 25));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane_daños.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextPane_daños.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane_daños);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 350, 120));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane_comentarios.setEditable(false);
        jTextPane_comentarios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextPane_comentarios.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTextPane_comentarios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 350, 120));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar equipo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 405, 200, 35));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 539));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int validacion = 0;
        
        String nombre, modelo, numero_serie, ultima_modificacion, fecha_ingreso, observaciones;
        
        String combo_tipo_equipo, combo_marca, combo_estatus;
       
        
        //recuperamos u obtenemos el valor de los txt mediante las variables declaradas para cada uno  
        nombre = txt_nombre.getText().trim();
        modelo = txt_modelo.getText().trim();
        numero_serie = txt_numero_serie.getText().trim();
        ultima_modificacion = txt_ultima_modificacion.getText().trim();
        fecha_ingreso = txt_fecha.getText().trim();
        
        //recuperamos el valor de los textpane
        observaciones = jTextPane_daños.getText();
        
        //recuperamos el valor de la selección de los combobox
        combo_tipo_equipo = combobox_tipo_equipo.getSelectedItem().toString();
        combo_marca = combobox_marca.getSelectedItem().toString();
        combo_estatus = combobox_estatus.getSelectedItem().toString();
      
        //validamos si los campos estan vacios        
         if (modelo.equals(""))
        {
         txt_modelo.setBackground(Color.red);
         validacion++;
        }
         
         if (numero_serie.equals(""))
        {
            txt_numero_serie.setBackground(Color.red);
            validacion++;
        }
          
          if (observaciones.equals(""))
        {
            jTextPane_daños.setText("Sin observaciones");
            validacion++;
        }
       
          
          if (validacion==0)
        {
            try
            {
                
                Connection cn  =Conexion.db();
               
                PreparedStatement pst = cn.prepareStatement("update equipos set tipo_equipo = ?, marca = ?, modelo = ?, num_serie = ?, Observaciones = ?, estatus = ? , ultima_modificacion = ? where id_equipo = "+IDEquipo);
                
                pst.setString(1, combo_tipo_equipo);
                pst.setString(2, combo_marca);
                pst.setString(3, modelo);
                pst.setString(4, numero_serie);
                pst.setString(5, observaciones);
                pst.setString(6, combo_estatus);
                pst.setString(7, user);
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                
                txt_nombre.setBackground(Color.green);
                txt_modelo.setBackground(Color.green);
                txt_numero_serie.setBackground(Color.green);
                txt_fecha.setBackground(Color.green);
                
                txt_ultima_modificacion.setText(user);
                
                jTextPane_daños.setBackground(Color.green);
                jTextPane_comentarios.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Equipo actualizado con éxito");
                
                this.dispose();
                
            } catch (HeadlessException | SQLException e)
            {
                System.err.println("Error en la instruccion actualizar");
            }
            
        }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InformacionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InformacionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InformacionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InformacionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_estatus;
    private javax.swing.JComboBox<String> combobox_marca;
    private javax.swing.JComboBox<String> combobox_tipo_equipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane_comentarios;
    private javax.swing.JTextPane jTextPane_daños;
    private javax.swing.JLabel label_comentarios;
    private javax.swing.JLabel label_estatus;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_modelo;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numero_serie;
    private javax.swing.JLabel label_reportes;
    private javax.swing.JLabel label_tipo_equipo;
    private javax.swing.JLabel label_titutlo;
    private javax.swing.JLabel label_ultima_modificacion;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero_serie;
    private javax.swing.JTextField txt_ultima_modificacion;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        txt_nombre.setText("");
        txt_modelo.setText("");
        txt_fecha.setText("");
        txt_numero_serie.setText("");
        
        jTextPane_daños.setText("");
    }

}
