/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
//libreria de la clase image

import java.awt.Image;
import java.awt.Toolkit;
//libreria de la clase icon
import javax.swing.Icon;
//libreria de la clase imageicon
import javax.swing.ImageIcon;

//libreria para poder realizar intrucciones de tipo sql
import java.sql.*;

//paquete para importar la clase que contiene la conexion a la db
import clases.Conexion;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Yader Jr
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    //variable para enviar datos entre interfaces
    public static String user = "";
    String pass = "";

    public Login() {
        initComponents();
        //metodo para las dimensiones de la interfaz
        setSize(400, 550);
        //metodo para que el usuario no modifique las dimensiones de la interfaz
        setResizable(false);
        //metodo para el titulo de la interfaz
        setTitle("Acceso al sistema");
        //metodo para centrar la interfaz al iniciar el programa
        setLocationRelativeTo(null);

        //codigo para el wallpaper de fondo azul difuminados
        
        //metodo de la clase imageicon para importar la imagen mediante el directorio
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //objeto de la clase icon dentro del constructor llamamos a la variable wallpaper lseguido del metodo getimage getscaledistance 
        //(traemos el label y obtenemos el ancho  por el metodo getWidth(), alto por el metodo getHeight(), y por ultimo la escala mediante la clase Image el metodo .scaledefault())
        //con este metodo adaptamos el tamaño de la imagen al label que contiene la imagen
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(),
                label_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        label_wallpaper.setIcon(icono);

        //metodo para que se apliquen los cambios realizados
        this.repaint();

        //codigo para la imagen del login 
        ImageIcon logo = new ImageIcon("src/images/DS.png");

        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(label_logo.getWidth(),
                label_logo.getHeight(), Image.SCALE_DEFAULT));

        label_logo.setIcon(icono_logo);

        this.repaint();

    }

    // metodo para cambiar el icono del jframe
    @Override
    public Image getIconImage() {
        //no necesita especificar la carpeta src el metodo ya sabe que se va a usar un archivo de esta carpeta
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_logo = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        button_acceso = new javax.swing.JButton();
        label_footer = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 270));

        txt_pass.setBackground(new java.awt.Color(153, 153, 255));
        txt_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 375, 210, -1));

        txt_username.setBackground(new java.awt.Color(153, 153, 255));
        txt_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));

        button_acceso.setBackground(new java.awt.Color(153, 153, 255));
        button_acceso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_acceso.setForeground(new java.awt.Color(255, 255, 255));
        button_acceso.setText("Acceder");
        button_acceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_accesoActionPerformed(evt);
            }
        });
        getContentPane().add(button_acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 35));

        label_footer.setText("Creado por Yader Barahona");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void button_accesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_accesoActionPerformed

        //variable que contendran lo que el usuario digite en los txt
        user = txt_username.getText().trim();

        pass = txt_pass.getText().trim();

        //condicion por si los campos no estan vacios y por si lo estan
        if (!user.equals("") || !pass.equals(""))
        {

            try
            {
                //llamado de la clase con el metodo de conexion a la db
                Connection cn = Conexion.db();

                //instruccion hacia la db   
                PreparedStatement pst = cn.prepareStatement("select tipo_nivel, estatus from usuarios where username  = '" + user
                        + "' and password = '" + pass + "'");

                //metodo para ejecutar la instruccion a la db
                ResultSet rs = pst.executeQuery();

                //condicion  si se cumple la instruccion a la db
                if (rs.next()){
                    
                    //variables para guardar lo que encontro la db y que nos lo retorne mediante el metodo getString
                    String tipo_nivel = rs.getString("tipo_nivel");
                    String estatus = rs.getString("estatus");
                    
                    //condiciones anidadas referente al tipo de cuenta ingresada
                    if(tipo_nivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")){
                        //metodo para destruir la interfaz actual y pasa a la interfaz referente al tipo de nivel
                        dispose();
                        
                        //metodo para ir a la interfaz referente al tipo de nivel (en este caso administrador)
                         new Administrador().setVisible(true);
                    } else if (tipo_nivel.equalsIgnoreCase("Capturista") && estatus.equalsIgnoreCase("Activo")){
                        dispose();
                        
                          new Capturista().setVisible(true);
                        
                    } else if(tipo_nivel.equalsIgnoreCase("Tecnico") && estatus.equalsIgnoreCase("Activo")){
                        dispose();
                        
                          new Tecnico().setVisible(true);
                        
                    }

                } else
                {
                    //optionpane para notificar que los datos de ingreso no existen en la db
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrecto");
                    txt_username.setText("");
                    txt_pass.setText("");
                }

            } catch (HeadlessException | SQLException e)
            {
                System.err.println("Error en el botón acceder" + e);
                JOptionPane.showMessageDialog(null, "¡¡Error al iniciar sesión, contacte al administrador!!");
            }

        } else
        {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }


    }//GEN-LAST:event_button_accesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_acceso;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
