/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Yader Jr
 */
public class RegistrarClientes extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    String user;

    public RegistrarClientes() {
        initComponents();

        user = Login.user;

        setSize(530, 350);
        setResizable(false);
        setTitle("Registrar nuevo cliente - sesión de " + user);
        setLocationRelativeTo(null);

        //metodo para evitar que el programa se ejecute en segundo plano cuando se cierre el mismo
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");

        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(), label_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));

        label_wallpaper.setIcon(icono);

        this.repaint();

    }
    
    @Override
    public Image getIconImage() {
        //no necesita especificar la carpeta src el metodo ya sabe que se va a usar un archivo de esta carpeta
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_registrar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        label_header = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        label_registrar = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_direccion = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        button_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(button_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 120, 100));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 200, 25));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 200, 25));

        txt_telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 200, 25));

        txt_direccion.setBackground(new java.awt.Color(153, 153, 255));
        txt_direccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        txt_direccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, 200, 25));

        label_header.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label_header.setForeground(new java.awt.Color(255, 255, 255));
        label_header.setText("Registro de clientes");
        getContentPane().add(label_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 5, -1, -1));

        label_footer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_footer.setForeground(new java.awt.Color(0, 0, 0));
        label_footer.setText("Creado por Yader Barahona");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        label_registrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_registrar.setForeground(new java.awt.Color(255, 255, 255));
        label_registrar.setText("Registrar cliente");
        getContentPane().add(label_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 200, -1, -1));

        label_nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        label_nombre.setText("Nombre");
        getContentPane().add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        label_email.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("Email");
        getContentPane().add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        label_telefono.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_telefono.setForeground(new java.awt.Color(255, 255, 255));
        label_telefono.setText("Teléfono");
        getContentPane().add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, -1, -1));

        label_direccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_direccion.setForeground(new java.awt.Color(255, 255, 255));
        label_direccion.setText("Dirección");
        getContentPane().add(label_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registrarActionPerformed
      
        int validacion = 0;
        String nombre,email, telefono, direccion;
        
        String ult_modificacion = user;
        
        nombre = txt_nombre.getText().trim();
        email = txt_email.getText().trim();
        telefono = txt_telefono.getText().trim();
        direccion = txt_direccion.getText().trim();
        
        if (nombre.equals(""))
        {
            txt_nombre.setBackground(Color.red);
            validacion++;
            
        }
        
         if (email.equals(""))
        {
            txt_email.setBackground(Color.red);
            validacion++;
            
        }
         
          if (telefono.equals(""))
        {
            txt_telefono.setBackground(Color.red);
            validacion++;
            
        }
          
           if (direccion.equals(""))
        {
            txt_direccion.setBackground(Color.red);
            validacion++;
            
        }
        
        if(validacion==0) {
        
        try
        {
            
            Connection cn = Conexion.db();
            PreparedStatement pst = cn.prepareStatement("insert into clientes values (?,?,?,?,?,?)");
            
            pst.setInt(1, 0);
            pst.setString(2, nombre);
            pst.setString(3, email);
            pst.setString(4, telefono);
            pst.setString(5, direccion);
            pst.setString(6, ult_modificacion);
            
            pst.executeUpdate();
            
            cn.close();
            
            Limpiar();
            
            txt_nombre.setBackground(Color.green);
            txt_email.setBackground(Color.green);
            txt_telefono.setBackground(Color.green);
            txt_direccion.setBackground(Color.green);

            JOptionPane.showMessageDialog(null, "Cliente registrado con éxito");
            
              this.dispose();
      
        } catch (HeadlessException | SQLException e)
        {
            System.err.println("Error en insertar el cliente");
            JOptionPane.showMessageDialog(null, "Error insertando el cliente, contacte al administrador");
        }
        
    }else{
    JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
}
    
        
    }//GEN-LAST:event_button_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_registrar;
    private javax.swing.JLabel label_direccion;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_registrar;
    private javax.swing.JLabel label_telefono;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

     public void Limpiar() {
        txt_nombre.setText("");
        txt_email.setText("");
        txt_telefono.setText("");
        txt_direccion.setText("");
     }

}
