/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Yader Jr
 */
public class Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form Tecnico
     */
    String user, nombre_usuario;
       int sesion_usuario;
       
    public Tecnico() {
        initComponents();
        setTitle("Técnico");
        setLocationRelativeTo(null);
        
         user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;

        setSize(550, 300);
        setResizable(false);
        setTitle("Técnico - sesión de " + user);
        this.setLocationRelativeTo(null);

        //condicional para controlar cuando se cierra o no por completo la interfaz de capturista o tecnico estando en administradore y estando en capturista o tecnico
        if (sesion_usuario == 1)
        {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        } else
        {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");

        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wallpaper.getWidth(), label_wallpaper.getHeight(),
                Image.SCALE_DEFAULT));

        label_wallpaper.setIcon(icono);
        this.repaint();
        
          try
        {
            //llamado de la clase conexion con el metodo db que contiene la conexion de a  la db
            Connection cn = Conexion.db();

            PreparedStatement pst = cn.prepareStatement(
                    "Select nombre_usuario from  usuarios where username = '" + user + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next())
            {
                nombre_usuario = rs.getString("nombre_usuario");
                label_titulo.setText("Bienvenido " + nombre_usuario);
            }

        } catch (SQLException e)
        {
            System.err.println("Error en conexion desde la interfaz tecnico ");
        }

    }
    
     @Override
    public Image getIconImage() {
        //no necesita especificar la carpeta src el metodo ya sabe que se va a usar un archivo de esta carpeta
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_gestion_equipo = new javax.swing.JButton();
        button_grafica_estatus = new javax.swing.JButton();
        button_grafica_marcas = new javax.swing.JButton();
        label_titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_gestion_equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        button_gestion_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gestion_equipoActionPerformed(evt);
            }
        });
        getContentPane().add(button_gestion_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 100));

        button_grafica_estatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        button_grafica_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_grafica_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(button_grafica_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 80, 120, 100));

        button_grafica_marcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        button_grafica_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_grafica_marcasActionPerformed(evt);
            }
        });
        getContentPane().add(button_grafica_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 120, 100));

        label_titulo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Bienvenido");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestión de equipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gráfica de estatus");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gráfica de marcas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Creado por Yader Barahona");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));
        getContentPane().add(label_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_gestion_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gestion_equipoActionPerformed
         GestionarEquipos gestionar_equipos = new GestionarEquipos();
         
         gestionar_equipos.setVisible(true);
    }//GEN-LAST:event_button_gestion_equipoActionPerformed

    private void button_grafica_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_grafica_estatusActionPerformed
         GraficaEstatus grafica_estatus = new GraficaEstatus();
         
         grafica_estatus.setVisible(true);
    }//GEN-LAST:event_button_grafica_estatusActionPerformed

    private void button_grafica_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_grafica_marcasActionPerformed
        GraficaMarcas grafica_marcas = new GraficaMarcas();
         
         grafica_marcas.setVisible(true);
    }//GEN-LAST:event_button_grafica_marcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_gestion_equipo;
    private javax.swing.JButton button_grafica_estatus;
    private javax.swing.JButton button_grafica_marcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_wallpaper;
    // End of variables declaration//GEN-END:variables
}
